#!/usr/bin/env node
/**
 * export_e2k_3cases.mjs — Genera 3 modelos .e2k para validación cruzada:
 *
 *   1) steelOnly      — Vigas W360x60 acero + Columnas HSS 250×10 acero (sin fill)
 *   2) filled         — Vigas W360x60 acero + Columnas CFT (Filled Steel Tube)
 *   3) concreteOnly   — Vigas concreto 0.30×0.60 + Columnas concreto 0.25×0.25
 *
 * Geometría idéntica para los 3:
 *   Bay 4×4 m, story h=4 m, mesh 4×4
 *   Losa concreto t=0.10, q=5 kN/m²
 *   Pin en base de columnas
 */
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

const Lx = 4, Ly = 4;
const slabZ = 4;
const t_slab = 0.10;
const q_unif = 5;
const nx = 4, ny = 4;
const nNx = nx + 1;
const dx = Lx / nx, dy = Ly / ny;

const E_c = 25e6, nu_c = 0.20;
const E_s = 200e6, nu_s = 0.30;

// W360x60 (steel I)
const W_h = 0.352, W_b = 0.203, W_tf = 0.013, W_tw = 0.008;

// HSS 250×250×10 (steel hollow tube)
const D_out = 0.250, t_HSS = 0.010;

// Concrete beam 0.30x0.60 (B×D)
const Cb_b = 0.30, Cb_d = 0.60;

// Concrete column 0.25×0.25
const Cc_b = 0.25, Cc_d = 0.25;


function generateE2k(caseId) {
  const lines = [];
  const isSteelOnly    = caseId === "steelOnly";
  const isFilled       = caseId === "filled";
  const isConcreteOnly = caseId === "concreteOnly";

  // Header
  lines.push(`$ File generated by export_e2k_3cases.mjs (case: ${caseId})`);
  lines.push(``);
  lines.push(`$ PROGRAM INFORMATION`);
  lines.push(`  PROGRAM  "ETABS"  VERSION "22.6.0"`);
  lines.push(``);
  lines.push(`$ CONTROLS`);
  lines.push(`  UNITS  "KN"  "M"  "C"  `);
  lines.push(`  TITLE2  "3-cases bench (${caseId})"`);
  lines.push(``);

  // Stories
  lines.push(`$ STORIES - IN SEQUENCE FROM TOP`);
  lines.push(`  STORY "Level_1"  HEIGHT 4 MASTERSTORY "Yes"  `);
  lines.push(`  STORY "Base"  ELEV 0`);
  lines.push(``);

  // Grids
  lines.push(`$ GRIDS`);
  lines.push(`  GRIDSYSTEM "G1"  TYPE "CARTESIAN"  BUBBLESIZE 1`);
  for (let i = 0; i <= nx; i++) {
    const lab = String.fromCharCode("A".charCodeAt(0) + i);
    lines.push(`  GRID "G1"  LABEL "${lab}"  DIR "X"  COORD ${i * dx}  VISIBLE "Yes"  BUBBLELOC "End"`);
  }
  for (let j = 0; j <= ny; j++) {
    lines.push(`  GRID "G1"  LABEL "${j + 1}"  DIR "Y"  COORD ${j * dy}  VISIBLE "Yes"  BUBBLELOC "Start"`);
  }
  lines.push(``);

  lines.push(`$ DIAPHRAGM NAMES`);
  lines.push(`  DIAPHRAGM "D1"    TYPE RIGID`);
  lines.push(``);

  // Materials — siempre incluimos ambos (concreto y acero) por simplicidad
  lines.push(`$ MATERIAL PROPERTIES`);
  lines.push(`  MATERIAL  "Mat_1"    TYPE "Concrete"    WEIGHTPERVOLUME 2.4`);
  lines.push(`  MATERIAL  "Mat_1"    SYMTYPE "Isotropic"  E ${E_c}  U ${nu_c}  A 1E-05`);
  lines.push(`  MATERIAL  "Mat_1"    FC 25000`);
  lines.push(`  MATERIAL  "Mat_2"    TYPE "Steel"    WEIGHTPERVOLUME 7.85`);
  lines.push(`  MATERIAL  "Mat_2"    SYMTYPE "Isotropic"  E ${E_s}  U 0.3  A 1E-05`);
  lines.push(`  MATERIAL  "Mat_2"    FY 345000  FU 450000  EFFFY 379500  EFFFU 495000`);
  lines.push(``);

  // Frame Sections
  lines.push(`$ FRAME SECTIONS`);
  if (isSteelOnly || isFilled) {
    // Vigas W360X60 acero
    lines.push(`  FRAMESECTION  "BeamSec"  MATERIAL "Mat_2"  SHAPE "Steel I/Wide Flange"  D ${W_h}  B ${W_b}  TF ${W_tf}  TW ${W_tw}`);
    if (isSteelOnly) {
      // Columnas HSS 250×10 (Hollow Tube — no fill)
      lines.push(`  FRAMESECTION  "ColSec"  MATERIAL "Mat_2"  SHAPE "Steel Tube"  D ${D_out}  B ${D_out}  TF ${t_HSS}  TW ${t_HSS}`);
    } else {
      // CFT compuesto (Filled Steel Tube)
      lines.push(`  FRAMESECTION  "ColSec"  MATERIAL "Mat_2"  SHAPE "Filled Steel Tube"  D ${D_out}  B ${D_out}  TF ${t_HSS}  TW ${t_HSS}  FILLMATERIAL "Mat_1"  `);
    }
  } else {
    // concreteOnly: vigas y columnas concreto
    lines.push(`  FRAMESECTION  "BeamSec"  MATERIAL "Mat_1"  SHAPE "Concrete Rectangular"  D ${Cb_d}  B ${Cb_b}`);
    lines.push(`  FRAMESECTION  "ColSec"   MATERIAL "Mat_1"  SHAPE "Concrete Rectangular"  D ${Cc_d}  B ${Cc_b}`);
  }
  lines.push(``);

  // Slab
  lines.push(`$ SLAB PROPERTIES`);
  lines.push(`  SHELLPROP  "Losa"  PROPTYPE  "Slab"  MATERIAL "Mat_1"  MODELINGTYPE "ShellThin"  SLABTYPE "Slab"  SLABTHICKNESS ${t_slab}`);
  lines.push(``);

  // Point coordinates
  lines.push(`$ POINT COORDINATES`);
  let pid = 0;
  for (let j = 0; j <= ny; j++) {
    for (let i = 0; i <= nx; i++) {
      pid++;
      lines.push(`  POINT "${pid}"  ${i * dx} ${j * dy} `);
    }
  }
  lines.push(``);

  // Line connectivities
  lines.push(`$ LINE CONNECTIVITIES`);
  let eid = 0;
  const beamPairs = [];
  for (let i = 0; i < nx; i++) beamPairs.push([i + 1, i + 2]);
  const topStart = ny * nNx;
  for (let i = 0; i < nx; i++) beamPairs.push([topStart + i + 1, topStart + i + 2]);
  for (let j = 0; j < ny; j++) beamPairs.push([j * nNx + 1, (j + 1) * nNx + 1]);
  for (let j = 0; j < ny; j++) beamPairs.push([j * nNx + nNx, (j + 1) * nNx + nNx]);
  for (const [a, b] of beamPairs) {
    eid++;
    lines.push(`  LINE  "E${eid}"  BEAM  "${a}"  "${b}"  0`);
  }
  const cornerPids = [1, nx + 1, ny * nNx + 1, ny * nNx + nNx];
  for (const cp of cornerPids) {
    eid++;
    lines.push(`  LINE  "E${eid}"  COLUMN  "${cp}"  "${cp}"  1`);
  }
  const lastBeamId = beamPairs.length;
  const colIds = [];
  for (let k = 0; k < 4; k++) colIds.push(lastBeamId + 1 + k);
  lines.push(``);

  // Area connectivities
  lines.push(`$ AREA CONNECTIVITIES`);
  let aid = 0;
  for (let j = 0; j < ny; j++) {
    for (let i = 0; i < nx; i++) {
      aid++;
      const p1 = j*nNx + i + 1;
      const p2 = p1 + 1;
      const p3 = (j+1)*nNx + i + 2;
      const p4 = (j+1)*nNx + i + 1;
      lines.push(`  AREA "F${aid}"  FLOOR  4  "${p1}"  "${p2}"  "${p3}"  "${p4}"  0  0  0  0  `);
    }
  }
  lines.push(``);

  // Point assigns
  lines.push(`$ POINT ASSIGNS`);
  for (let i = 1; i <= nNx * (ny + 1); i++) {
    lines.push(`  POINTASSIGN  "${i}"  "Level_1"  DIAPH "D1"  `);
  }
  for (const cp of cornerPids) {
    // EMPOTRAMIENTO COMPLETO en base (UX UY UZ RX RY RZ) - no PIN
    lines.push(`  POINTASSIGN  "${cp}"  "Base"  RESTRAINT "UX UY UZ RX RY RZ"  `);
  }
  lines.push(``);

  // Line assigns
  lines.push(`$ LINE ASSIGNS`);
  for (let i = 1; i <= beamPairs.length; i++) {
    lines.push(`  LINEASSIGN  "E${i}"  "Level_1"  SECTION "BeamSec"  MINNUMSTA 3 AUTOMESH "YES"  MESHATINTERSECTIONS "YES"  `);
  }
  for (const eId of colIds) {
    lines.push(`  LINEASSIGN  "E${eId}"  "Level_1"  SECTION "ColSec"  MINNUMSTA 3 AUTOMESH "YES"  MESHATINTERSECTIONS "YES"  `);
  }
  lines.push(``);

  // Area assigns
  lines.push(`$ AREA ASSIGNS`);
  aid = 0;
  for (let j = 0; j < ny; j++) {
    for (let i = 0; i < nx; i++) {
      aid++;
      lines.push(`  AREAASSIGN  "F${aid}"  "Level_1"  SECTION "Losa"  DIAPH  "D1"  OBJMESHTYPE "DEFAULT"  ADDRESTRAINT "Yes"  CARDINALPOINT "TOP"  TRANSFORMSTIFFNESSFOROFFSETS "No"  `);
    }
  }
  lines.push(``);

  // Loads
  lines.push(`$ LOAD PATTERNS`);
  lines.push(`  LOADPATTERN "Dead"  TYPE  "Dead"  SELFWEIGHT  0`);
  lines.push(`  LOADPATTERN "Live"  TYPE  "Live"  SELFWEIGHT  0`);
  lines.push(``);
  lines.push(`$ POINT OBJECT LOADS`);
  lines.push(``);
  lines.push(`$ SHELL OBJECT LOADS`);
  aid = 0;
  for (let j = 0; j < ny; j++) {
    for (let i = 0; i < nx; i++) {
      aid++;
      lines.push(`  AREALOAD  "F${aid}"  "Level_1"  TYPE "UNIFF"  DIR "GRAV"  LC "Dead"  FVAL ${q_unif} `);
    }
  }
  lines.push(``);

  // Analysis options
  lines.push(`$ ANALYSIS OPTIONS`);
  lines.push(`  ACTIVEDOF "UX UY UZ RX RY RZ"`);
  lines.push(`  PDELTA  METHOD "NONE"`);
  lines.push(`  AUTOMESHOPTIONS  MESHTYPE  "GENERAL"  FLOORMESHMAXSIZE  1.0 WALLMESHMAXSIZE  1.0`);
  lines.push(``);
  lines.push(`$ MASS SOURCE`);
  lines.push(`  MASSSOURCE  "MsSrc1"    INCLUDEELEMENTS "Yes"    INCLUDEADDEDMASS "No"    INCLUDELOADS "No"    ISDEFAULT "Yes"`);
  lines.push(``);
  lines.push(`$ LOAD CASES`);
  lines.push(`  LOADCASE "Dead"  TYPE  "Linear Static"  INITCOND  "PRESET"`);
  lines.push(`  LOADCASE "Dead"  LOADPAT  "Dead"  SF  1`);
  lines.push(`  LOADCASE "Live"  TYPE  "Linear Static"  INITCOND  "PRESET"`);
  lines.push(`  LOADCASE "Live"  LOADPAT  "Live"  SF  1`);
  lines.push(``);
  lines.push(`  END`);
  lines.push(`$ END OF MODEL FILE`);

  return lines.join("\r\n");
}

const CASES = ["steelOnly", "filled", "concreteOnly"];
const outDir = join(__dirname, "etabs_3cases");
if (!existsSync(outDir)) mkdirSync(outDir);

console.log("=== Generador .e2k 3 cases (steelOnly | filled | concreteOnly) ===");
for (const c of CASES) {
  const txt = generateE2k(c);
  const outPath = join(outDir, `case_${c}.e2k`);
  writeFileSync(outPath, txt, "utf8");
  console.log(`[OK] ${outPath}`);
}
