# -*- coding: utf-8 -*-
"""
Genera 2 archivos .e2k de edificio idéntico:
  - edif_membrane.e2k       → MODELINGTYPE "Membrane"
  - edif_semirigid_shell.e2k → MODELINGTYPE "ShellThin" + SEMIRIGID Diaphragm

Edificio 3×3 vanos (4×4 cols) × 3 pisos. Vanos 5m. Pisos 3m. Hormigón f'c=210.
Cols 40×40, vigas 30×40, losa 0.15m.

USO: ejecutar este script. Genera 2 .e2k. Después abrir en ETABS via
File → Import → ETABS Text File (.e2k).
"""
import os, sys

sys.stdout.reconfigure(encoding='utf-8')
OUT = os.path.dirname(os.path.abspath(__file__))

NX, NY = 3, 3              # vanos
DX, DY = 5.0, 5.0
NP = 3
HP = 3.0
LOSA_E = 0.15
COL_B, COL_H = 0.40, 0.40
VIG_B, VIG_H = 0.30, 0.40

# Hormigón f'c=210 → E ≈ 21459 MPa = 21459000 kN/m²
E_KNM2 = 21458891.0
NU = 0.2
RHO_KNM3 = 24.0


def generate_e2k(slab_modeling_type, diaphragm_type, out_filename, title):
    """
    slab_modeling_type: "Membrane" | "ShellThin"
    diaphragm_type:     "RIGID" | "SEMIRIGID"
    """
    lines = []
    add = lines.append

    add("$ File generated by Hekatan validation script")
    add("")
    add("$ PROGRAM INFORMATION")
    add('  PROGRAM  "ETABS"  VERSION "22.3.0"')
    add("")
    add("$ CONTROLS")
    add('  UNITS  "KN"  "M"  "C"')
    add(f'  TITLE1  "{title}"')
    add('  PREFERENCE  MERGETOL 0.001')
    add('  RLLF  METHOD "ASCE7-10"  USEDEFAULTMIN "YES"')
    add("")
    # Stories
    add("$ STORIES - IN SEQUENCE FROM TOP")
    for ip in range(NP, 0, -1):
        if ip == NP:
            add(f'  STORY "Story{ip}"  HEIGHT {HP} MASTERSTORY "Yes"')
        else:
            add(f'  STORY "Story{ip}"  HEIGHT {HP} SIMILARTO "Story{NP}"')
    add('  STORY "Base"  ELEV 0')
    add("")
    # Grids
    add("$ GRIDS")
    add('  GRIDSYSTEM "G1"  TYPE "CARTESIAN"  BUBBLESIZE 1')
    for ix in range(NX+1):
        label = chr(ord('A') + ix)
        add(f'  GRID "G1"  LABEL "{label}"  DIR "X"  COORD {ix*DX} VISIBLE "Yes"  BUBBLELOC "End"')
    for iy in range(NY+1):
        add(f'  GRID "G1"  LABEL "{iy+1}"  DIR "Y"  COORD {iy*DY} VISIBLE "Yes"  BUBBLELOC "Start"')
    add("")
    # Diaphragm
    add("$ DIAPHRAGM NAMES")
    add(f'  DIAPHRAGM "D1"  TYPE {diaphragm_type}')
    add("")
    # Material
    add("$ MATERIAL PROPERTIES")
    add(f'  MATERIAL  "concrete"  TYPE "Concrete"  WEIGHTPERVOLUME {RHO_KNM3}')
    add(f'  MATERIAL  "concrete"  SYMTYPE "Isotropic"  E {E_KNM2}  U {NU}  A 1.0E-05')
    add('  MATERIAL  "concrete"  FC 28000')
    add("")
    # Frame Sections
    add("$ FRAME SECTIONS")
    add(f'  FRAMESECTION  "COL"  MATERIAL "concrete"  SHAPE "Concrete Rectangular"  D {COL_H} B {COL_B}')
    add(f'  FRAMESECTION  "VIG"  MATERIAL "concrete"  SHAPE "Concrete Rectangular"  D {VIG_H} B {VIG_B}')
    add("")
    # Concrete sections (pueden quedarse default para frames)
    add("$ CONCRETE SECTIONS")
    add('  CONCRETESECTION  "COL"  TYPE "Column"  PATTERN "R-3-3"  TRANSREINF "TIES"  COVER 0.04 NUMCONFINEBARS3 3 NUMCONFINEBARS2 3')
    add('  CONCRETESECTION  "VIG"  TYPE "Beam"  COVERTOP 0.06 COVERBOTTOM 0.06')
    add("")
    # Slab Properties (la clave)
    add("$ SLAB PROPERTIES")
    add(f'  SHELLPROP  "slab"  PROPTYPE  "Slab"  MATERIAL "concrete"  MODELINGTYPE "{slab_modeling_type}"  SLABTYPE "Slab"  SLABTHICKNESS {LOSA_E}')
    add("")

    # Points (planta solamente — ETABS los replica en cada piso por POINTASSIGN)
    add("$ POINT COORDINATES")
    pid = 1
    pmap = {}
    for iy in range(NY+1):
        for ix in range(NX+1):
            x, y = ix*DX, iy*DY
            add(f'  POINT "{pid}"  {x} {y}')
            pmap[(ix,iy)] = pid
            pid += 1
    add("")
    # Lines
    add("$ LINE CONNECTIVITIES")
    line_id = 1
    cols_lines = []
    for iy in range(NY+1):
        for ix in range(NX+1):
            p = pmap[(ix,iy)]
            add(f'  LINE "C{line_id}"  COLUMN  "{p}"  "{p}"  1')
            cols_lines.append(f"C{line_id}")
            line_id += 1
    beams_lines = []
    for iy in range(NY+1):
        for ix in range(NX):
            p1 = pmap[(ix,iy)]; p2 = pmap[(ix+1,iy)]
            name = f"BX{line_id}"
            add(f'  LINE "{name}"  BEAM  "{p1}"  "{p2}"  0')
            beams_lines.append(name)
            line_id += 1
    for iy in range(NY):
        for ix in range(NX+1):
            p1 = pmap[(ix,iy)]; p2 = pmap[(ix,iy+1)]
            name = f"BY{line_id}"
            add(f'  LINE "{name}"  BEAM  "{p1}"  "{p2}"  0')
            beams_lines.append(name)
            line_id += 1
    add("")
    # Areas (losas)
    add("$ AREA CONNECTIVITIES")
    area_id = 1
    floors_areas = []
    for iy in range(NY):
        for ix in range(NX):
            p1 = pmap[(ix,iy)]; p2 = pmap[(ix+1,iy)]
            p3 = pmap[(ix+1,iy+1)]; p4 = pmap[(ix,iy+1)]
            name = f"F{area_id}"
            add(f'  AREA "{name}"  FLOOR  4  "{p1}"  "{p2}"  "{p3}"  "{p4}"  0  0  0  0')
            floors_areas.append(name)
            area_id += 1
    add("")
    # Point Assigns (replicar puntos en cada piso + restraints en base)
    add("$ POINT ASSIGNS")
    for ip in range(NP, 0, -1):
        for iy in range(NY+1):
            for ix in range(NX+1):
                p = pmap[(ix,iy)]
                add(f'  POINTASSIGN  "{p}"  "Story{ip}"  DIAPH "D1"')
    # Base restraints
    for iy in range(NY+1):
        for ix in range(NX+1):
            p = pmap[(ix,iy)]
            add(f'  POINTASSIGN  "{p}"  "Base"  RESTRAINT "UX UY UZ RX RY RZ"  DIAPH "DISCONNECTED"')
    add("")
    # Line Assigns
    add("$ LINE ASSIGNS")
    for ln in cols_lines:
        for ip in range(1, NP+1):
            add(f'  LINEASSIGN  "{ln}"  "Story{ip}"  SECTION "COL"  RIGIDZONE 0  MINNUMSTA 2')
    for ln in beams_lines:
        for ip in range(1, NP+1):
            add(f'  LINEASSIGN  "{ln}"  "Story{ip}"  SECTION "VIG"  RIGIDZONE 0  MINNUMSTA 2')
    add("")
    # Area Assigns
    add("$ AREA ASSIGNS")
    for fa in floors_areas:
        for ip in range(1, NP+1):
            add(f'  AREAASSIGN  "{fa}"  "Story{ip}"  SECTION "slab"  DIAPHRAGMTOFLOOR  "Yes" DIAPH "D1"')
    add("")
    # Load Patterns (DEAD + LIVE)
    add("$ LOAD PATTERNS")
    add('  LOADPATTERN "DEAD"  TYPE "Dead"  SELFWEIGHT 1')
    add('  LOADPATTERN "LIVE"  TYPE "Live"  SELFWEIGHT 0')
    add("")
    # Analysis Options
    add("$ ANALYSIS OPTIONS")
    add('  ACTIVEDOF "UX UY UZ RX RY RZ"')
    add('  PDELTA  METHOD "NONE"')
    add('  AUTOMESHOPTIONS  MESHTYPE  "GENERAL"  FLOORMESHMAXSIZE  1.25 WALLMESHMAXSIZE  1.25')
    add("")
    # Mass Source
    add("$ MASS SOURCE")
    add('  MASSSOURCE  "MsSrc1"    INCLUDEELEMENTS "Yes"    INCLUDEADDEDMASS "No"    INCLUDELOADS "Yes"    INCLUDEMOVE "No"    INCLUDELATERALMASS "Yes"    INCLUDEVERTICALMASS "Yes"    LUMPATSTORIES "Yes"    ISDEFAULT "Yes"')
    add('  MASSSOURCELOAD  "MsSrc1"  "DEAD"  1')
    add('  MASSSOURCELOAD  "MsSrc1"  "LIVE"  0.25')
    add("")
    # Load Cases (Modal con sintaxis correcta)
    add("$ LOAD CASES")
    add('  LOADCASE "Modal"  TYPE  "Modal - Eigen"  INITCOND  "PRESET"')
    add('  LOADCASE "Modal"  MAXMODES  12 MINMODES  1 EIGENSHIFTFREQ  0 EIGENCUTOFF  0 EIGENTOL  1E-09')
    add('  LOADCASE "Dead"  TYPE  "Linear Static"  INITCOND  "PRESET"')
    add('  LOADCASE "Dead"  LOADPAT  "DEAD"  SF  1')
    add('  LOADCASE "Live"  TYPE  "Linear Static"  INITCOND  "PRESET"')
    add('  LOADCASE "Live"  LOADPAT  "LIVE"  SF  1')
    add("")
    add("$ LOG")
    add("  STARTCOMMENTS")
    add("")
    add("  ENDCOMMENTS")
    add("")
    add("  END")
    add("$ END OF MODEL FILE")

    text = "\n".join(lines)
    out_path = os.path.join(OUT, out_filename)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"  Generado: {out_path}")
    print(f"    Líneas: {len(lines)}, Slab: {slab_modeling_type}, Diaphragm: {diaphragm_type}")
    return out_path


print("Generando .e2k files…\n")

p1 = generate_e2k(
    slab_modeling_type="Membrane",
    diaphragm_type="SEMIRIGID",
    out_filename="edif_membrane.e2k",
    title="Edificio 3x3x3 vanos · LOSA MEMBRANE · SEMIRIGID Diaphragm")

p2 = generate_e2k(
    slab_modeling_type="ShellThin",
    diaphragm_type="SEMIRIGID",
    out_filename="edif_semirigid_shell.e2k",
    title="Edificio 3x3x3 vanos · LOSA SHELLTHIN · SEMIRIGID Diaphragm")

p3 = generate_e2k(
    slab_modeling_type="ShellThin",
    diaphragm_type="RIGID",
    out_filename="edif_rigid_shell.e2k",
    title="Edificio 3x3x3 vanos · LOSA SHELLTHIN · RIGID Diaphragm")

print("\n[OK] Generación completa.")
print("\nINSTRUCCIONES:")
print("  1. Abrir ETABS 22")
print("  2. File → Import → ETABS Text File (.e2k)")
print(f"  3. Seleccionar uno de los 3 archivos generados:")
print(f"     - {os.path.basename(p1)}")
print(f"     - {os.path.basename(p2)}")
print(f"     - {os.path.basename(p3)}")
print("  4. F5 → Run Analysis")
print("  5. python 11_solo_lee_modos.py para extraer modos")
